2024-04-20 21:37:18,139 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-20 21:37:18,140 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Configure stats pid to 1548
2024-04-20 21:37:18,140 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Loading settings from /Users/tony/.config/wandb/settings
2024-04-20 21:37:18,140 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Loading settings from /Users/tony/convergence_sr/wandb/settings
2024-04-20 21:37:18,140 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-20 21:37:18,140 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-20 21:37:18,140 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-20 21:37:18,140 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-20 21:37:18,140 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-20 21:37:18,140 INFO    MainThread:1548 [wandb_init.py:_log_setup():521] Logging user logs to /Users/tony/convergence_sr/wandb/run-20240420_213718-izr8808v/logs/debug.log
2024-04-20 21:37:18,140 INFO    MainThread:1548 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/tony/convergence_sr/wandb/run-20240420_213718-izr8808v/logs/debug-internal.log
2024-04-20 21:37:18,140 INFO    MainThread:1548 [wandb_init.py:_jupyter_setup():467] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x158bf20d0>
2024-04-20 21:37:18,140 INFO    MainThread:1548 [wandb_init.py:init():561] calling init triggers
2024-04-20 21:37:18,140 INFO    MainThread:1548 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-04-20 21:37:18,140 INFO    MainThread:1548 [wandb_init.py:init():611] starting backend
2024-04-20 21:37:18,140 INFO    MainThread:1548 [wandb_init.py:init():615] setting up manager
2024-04-20 21:37:18,143 INFO    MainThread:1548 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-04-20 21:37:18,146 INFO    MainThread:1548 [wandb_init.py:init():623] backend started and connected
2024-04-20 21:37:18,163 INFO    MainThread:1548 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-20 21:37:18,163 INFO    MainThread:1548 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-20 21:37:18,163 INFO    MainThread:1548 [wandb_init.py:init():715] updated telemetry
2024-04-20 21:37:18,202 INFO    MainThread:1548 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-20 21:37:18,498 ERROR   MainThread:1548 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-20 21:37:18,637 ERROR   MainThread:1548 [wandb_init.py:init():1199] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/Users/tony/venvs/_Users_tony_convergence_sr_.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
          ^^^^^^^^^
  File "/Users/tony/venvs/_Users_tony_convergence_sr_.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-20 21:37:38,690 INFO    MainThread:1548 [wandb_settings.py:_apply_login():1943] Applying login settings: {}
2024-04-20 21:37:38,760 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-20 21:37:38,761 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Configure stats pid to 1548
2024-04-20 21:37:38,761 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Loading settings from /Users/tony/.config/wandb/settings
2024-04-20 21:37:38,761 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Loading settings from /Users/tony/convergence_sr/wandb/settings
2024-04-20 21:37:38,761 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-20 21:37:38,761 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-20 21:37:38,761 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-20 21:37:38,761 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-20 21:37:38,761 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-20 21:37:38,762 INFO    MainThread:1548 [wandb_init.py:_log_setup():521] Logging user logs to /Users/tony/convergence_sr/wandb/run-20240420_213738-5mwnhomb/logs/debug.log
2024-04-20 21:37:38,762 INFO    MainThread:1548 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/tony/convergence_sr/wandb/run-20240420_213738-5mwnhomb/logs/debug-internal.log
2024-04-20 21:37:38,762 INFO    MainThread:1548 [wandb_init.py:init():561] calling init triggers
2024-04-20 21:37:38,762 INFO    MainThread:1548 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-04-20 21:37:38,762 INFO    MainThread:1548 [wandb_init.py:init():611] starting backend
2024-04-20 21:37:38,762 INFO    MainThread:1548 [wandb_init.py:init():615] setting up manager
2024-04-20 21:37:38,764 INFO    MainThread:1548 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-04-20 21:37:38,765 INFO    MainThread:1548 [wandb_init.py:init():623] backend started and connected
2024-04-20 21:37:38,773 INFO    MainThread:1548 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-20 21:37:38,773 INFO    MainThread:1548 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-20 21:37:38,773 INFO    MainThread:1548 [wandb_init.py:init():715] updated telemetry
2024-04-20 21:37:38,774 INFO    MainThread:1548 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-20 21:37:39,268 INFO    MainThread:1548 [wandb_run.py:_on_init():2357] communicating current version
2024-04-20 21:37:39,312 WARNING MsgRouterThr:1548 [router.py:message_loop():77] message_loop has been closed
2024-04-20 21:38:09,521 INFO    MainThread:1548 [wandb_init.py:init():799] starting run threads in backend
2024-04-20 21:38:39,903 INFO    MainThread:1548 [wandb_run.py:_console_start():2335] atexit reg
2024-04-20 21:38:39,904 INFO    MainThread:1548 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-04-20 21:38:39,904 INFO    MainThread:1548 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-04-20 21:38:39,904 INFO    MainThread:1548 [wandb_run.py:_redirect():2280] Redirects installed.
2024-04-20 21:38:39,906 INFO    MainThread:1548 [wandb_init.py:init():842] run started, returning control to user process
2024-04-20 21:38:39,906 INFO    MainThread:1548 [wandb_watch.py:watch():51] Watching
2024-04-20 21:41:34,907 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-20 21:41:34,908 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Configure stats pid to 1548
2024-04-20 21:41:34,908 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Loading settings from /Users/tony/.config/wandb/settings
2024-04-20 21:41:34,908 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Loading settings from /Users/tony/convergence_sr/wandb/settings
2024-04-20 21:41:34,908 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-20 21:41:34,908 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-20 21:41:34,908 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-20 21:41:34,908 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-20 21:41:34,908 INFO    MainThread:1548 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-20 21:41:34,908 INFO    MainThread:1548 [wandb_init.py:_log_setup():521] Logging user logs to /Users/tony/convergence_sr/wandb/run-20240420_214134-bgh8gz1l/logs/debug.log
2024-04-20 21:41:34,908 INFO    MainThread:1548 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/tony/convergence_sr/wandb/run-20240420_214134-bgh8gz1l/logs/debug-internal.log
2024-04-20 21:41:34,909 INFO    MainThread:1548 [wandb_init.py:init():561] calling init triggers
2024-04-20 21:41:34,909 INFO    MainThread:1548 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-04-20 21:41:34,909 INFO    MainThread:1548 [wandb_init.py:init():586] re-initializing run, found existing run on stack: 5mwnhomb
2024-04-20 21:41:34,910 INFO    MainThread:1548 [wandb_run.py:_finish():2064] finishing run tony_t_liu/full_precision_train/5mwnhomb
2024-04-20 21:41:34,911 INFO    MainThread:1548 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-04-20 21:41:34,912 INFO    MainThread:1548 [wandb_run.py:_restore():2287] restore
2024-04-20 21:41:34,913 INFO    MainThread:1548 [wandb_run.py:_restore():2293] restore done
2024-04-20 21:42:15,818 INFO    MainThread:1548 [wandb_init.py:init():611] starting backend
2024-04-20 21:42:15,818 INFO    MainThread:1548 [wandb_init.py:init():615] setting up manager
2024-04-20 21:42:15,822 INFO    MainThread:1548 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-04-20 21:42:15,831 INFO    MainThread:1548 [wandb_init.py:init():623] backend started and connected
2024-04-20 21:42:15,868 INFO    MainThread:1548 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-20 21:42:15,868 INFO    MainThread:1548 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-20 21:42:15,868 INFO    MainThread:1548 [wandb_init.py:init():715] updated telemetry
2024-04-20 21:42:15,873 INFO    MainThread:1548 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
